from .products import products_bp
from .users import users_bp
from .sales import sales_bp
from .suppliers import suppliers_bp
from .purchases import purchases_bp
from .transactions import transactions_bp
from .tools import tools_bp
from .api_users import api_users_bp
from .api_products import api_products_bp
from .api_sales import api_sales_bp
from .api_transactions import api_transactions_bp